name: Automerge Renovate

on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "!wip"
          MERGE_COMMIT_MESSAGE: "automatic"
          MERGE_FILTER_AUTHOR: "renovate[bot]"
          MERGE_FILTER_FILE_PATTERNS: "package.json,package-lock.json"