name: Build

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set git user
        run: |
          git config --global user.email "picocodes@gmail.com"
          git config --global user.name "picocodes"

      - name: Increment version
        id: npm_bump
        run: |
          version=$(npm version patch -m "Increment version [skip ci]")
          echo "new_version=$version" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: "picocodes"
          commit_user_email: "picocodes@gmail.com"
          commit_message: "Build and increment version [skip ci]"
          commit_options: '--no-verify --allow-empty'
          push_options: '--force'